name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - uses: nicknovitski/nix-develop@v1

    - uses: Swatinem/rust-cache@v2
      
    - name: Build
      run: cargo build --release --verbose
      
    - name: Run basic tests (does not include primary ./test.py tests)
      run: cargo test --release --verbose
      
    - name: Check formatting
      run: cargo fmt --check --verbose
